### ISSUE TITLE
"Where is code" link broken

### ISSUE THREAD

**Issue by Skatox** [devtools-html/docs#3]
On getting started section, the link "Where is the code" should be updated to http://docs.firefox-dev.tools/getting-started/where-is-the-code.html 

I would like to fix it, do I need to report it at mozilla and update it from Firefox's source code?

**Comment by sole** [comment]
Hey @Skatox, yes, the code is in Firefox's source code, in `/devtools/docs`

I see that the link has a duplicated `getting-started` on the path, as do other links in this document: /devtools/docs/getting-started/README.md - since all of them are in the same folder they don't need the `getting-started` bit.

I think you already have a Bugzilla account as I've seen you posting there. We need to associate code changes to a bug, so would you mind opening one before you send the changes?
Let me know when you have it and I can help you with reviewing, etc :)

And thank you so much!

**Comment by Skatox** [comment]
Thanks for the reply. I also found another bug and I reported at https://bugzilla.mozilla.org/show_bug.cgi?id=1408827 thanks for guiding me.

**Comment by sukrosono** [comment]
So the correct is fix the automation process or we take changes directly on the mercurial repository?

@Skatox You are still working on it?

**Comment by Skatox** [comment]
Yes, I gonna work on it next week. I've been busy.

**Comment by sukrosono** [comment]
Glad to hear that, but where you work? via upper repo (mercurial base repo)? I don't know the appropriate process, but want to make sure we take the proper one to prevent redundant work :smile: ,

**Comment by Skatox** [comment]
I'll be working trough bugzilla using firefox's central repo.
